<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>denso_bringup</name>
  <version>0.0.0</version>
  <description>Launch files for denso robot arm</description>
  <maintainer email="coenheerink@outlook.com">coen</maintainer>
  <license>M.I.T.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>control_msgs</depend>
  <depend>control_toolbox</depend>
  <depend>gz_ros2_control</depend>
  <depend>hardware_interface</depend>
  <depend>ros_gz</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_image</depend>
  <depend>ros_gz_sim</depend>
  <depend>rosbridge_server</depend>
  <depend>usb_cam</depend>
  <depend>v4l2_camera</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <exec_depend>denso_description</exec_depend>
  <exec_depend>denso_hardware_interface</exec_depend>
  <exec_depend>denso_moveit_config</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>