# MoveIt uses this configuration for controller management
# The MoveItControllerManager can parse the joint names in any command coming from
# MoveIt and activate the appropriate controllers of ROS2 control
# try to write command on the same line of attribute. Don't write them in a seperate line.
# Ex: this is not allowed, may cause unexpected error:
#   Type: GripperCommand
#   # dummy comment

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - denso_arm_controller
    - denso_hand_controller

  denso_arm_controller:
    type: FollowJointTrajectory   # type of "action"
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    action_ns: follow_joint_trajectory
    default: true

  denso_hand_controller:
    type: GripperCommand
    joints:
      - gripper_gear_right_joint
    action_ns: gripper_cmd
    default: true
    
trajectory_execution:
  execution_duration_monitoring: true  # Enable monitoring for simplicity
  allowed_goal_duration_margin: 2.5     # allows an extra 2 seconds beyond expected duration
  allowed_start_tolerance: 0.5       # tolerance for trajectory start point validation
